# Standards: 0.11
---

# 1.1.2 Ensure separate partition exists for /tmp (Scored)

- name: 1.1.2 - Ensure separate partition exists for /tmp (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
  with_items:
    - { mountpoint: '/tmp', device: 'tmpfs', fstype: 'tmpfs' }
  tags:
      - level-1
      - section-1
      - "1.1.2"
      - scored
